### ISSUE TITLE
DB driver

### ISSUE THREAD

**Issue by cosminwindox** [GHMatti/ghmattimysql#10]
Hello, im trying to start the server in linux but give me this error...

[vRP] DB driver "ghmattimysql" not initialized yet (44 prepares cached, 7 queries cached).

**Comment by hellsvien** [comment]
Some help would be awesome hey.

**Comment by mteverst** [comment]
I am also having this issue!

**Comment by PotatoCast** [comment]
Im also having the same problem

**Comment by GHMatti** [comment]
Use FiveM-MySQL instead.

**Comment by ttibau** [comment]
`[vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached)`

Im also having the same problem 

Use FiveM-MySQL not solved.

**Comment by GHMatti** [comment]
Shouldn't you post it on the offical or the FiveM-MySQL repository instead?

https://github.com/ImagicTheCat/vRP-db-drivers
