### ISSUE TITLE
Can't get certain parameters to work.

### ISSUE THREAD

**Issue by RussianRonin** [GHMatti/ghmattimysql#14]
I cannot get this parameter format to work:

`("SELECT * FROM ronin_users WHERE steamid = @steamid",{['steamid'] = steamIdentifier}, function(results)`

The parameter acts like it doesn't exist. The debug shows nothing in the parameters form. This is lua btw.

The ? parameter format does work but seems a lot more limited.

**Comment by TheDumpap** [comment]
You have to use the @ symbol in the parameter list aswell.
` exports.ghmattimysql:execute(""SELECT * FROM ronin_users WHERE steamid = @steamid;",
        {
            ['@steamid'] = steamidentifier
        }, function(result)`

**Comment by GHMatti** [comment]
Fixed. Works now with or without the @.
