### ISSUE TITLE
Latest Version Unzip Issue

### ISSUE THREAD

**Issue by rhapidfyre** [GHMatti/ghmattimysql#15]
Trouble extracting the latest version from the zip. No matter where I extract it, on either computer, I get "an unexpected error has occurred" for everything except the ui/fonts/ directory. Going to try later versions to see if they work. The master works, but not 1.2.1.

[Edit] Turns out there's no release 1.2.0 available. Everything unzips just fine except the release version of 1.2.1.

[Final edit] Turns out it's just windows. Using 7zip works. You're using a compression that windows doesn't recognize.

**Comment by rhapidfyre** [comment]
Version 1.2.0 unzipped with no issue.

**Comment by GHMatti** [comment]
I am using BZip compression. I might be doing this just to annoy people.
