### ISSUE TITLE
 [vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached).

### ISSUE THREAD

**Issue by Frederikkudsk12** [GHMatti/ghmattimysql#19]
I have the vrp_ghmattimysql & GHMattiMySQL on my server but its still don't work for me its just says (  [vRP] DB driver "ghmattimysql" not initialized yet (39 prepares cached, 5 queries cached). )

**Comment by steevLP** [comment]
i am sorry for a that late response but as far as i got it working you do just need to add the module inside the vrp db driver and it will connect

**Comment by GHMatti** [comment]
I think you need to be running the old C# version, see readme.
