### ISSUE TITLE
[DEP0095],[DEP0126],[DEP0096] DeprecationWarnings

### ISSUE THREAD

**Issue by stianhje** [GHMatti/ghmattimysql#20]
![6cc2a8c851eec49228c2194b93231e2a](https://user-images.githubusercontent.com/48527532/70855002-f10f7700-1ec3-11ea-87d3-436386eb0810.png)

**Comment by rhapidfyre** [comment]
Also getting this

**Comment by GHMatti** [comment]
Closed and fixed.
