### ISSUE TITLE
Windows Incompatibility

### ISSUE THREAD

**Issue by wills-web** [GHMatti/ghmattimysql#21]
An exception is thrown when utilising the execute export for this library **in a Windows environment** (Ubuntu 18.04 environment works perfectly). While the actual execute command is carried out (an insert statement results in data being inserted into the database), an FXServer crash is experienced shortly after. Investigation of [the dump file created](https://drive.google.com/file/d/1NiekcOzalFK87x2V0VmOuPiM0u_o9ZnF/view?usp=sharing), the following exception message is generated.

> The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

The below C# snippet is the method used to generate the error thrown. Note: this error is thrown with all types of MySQL transactions (INSERT, UPDATE, DELETE, etc).

```
ExportDictionary Exports = new ExportDictionary();
Exports["ghmattimysql"].execute(
    "INSERT INTO `dev`.`fines` (`given_to`, `given_by`, `comment`) VALUES (1, 2, 'Test comment');");
```
Again, to stress, this code results in a new row being added to the table, but the error is thrown shortly after.

Below is the very end of the console output from a local Windows testing server.
```
cfx> Thread 000000000000491C may have been prematurely finalized
* Assertion at W:\cf\mono\mono\utils\mono-threads.c:634, condition `info' not met

Thread 000000000000491C may have been prematurely finalized
network thread hitch warning: timer interval of 449 milliseconds


=================================================================
FXServer crashed.
A minidump can be found at D:\flashpoint-fivem\server\crashes\1f5a3499-dc3a-4871-8a5e-29337cf92102.dmp.
Failed to automatically report the crash. Please submit the minidump to the project developers.
=================================================================
```
[Console Output Image](https://i.gyazo.com/8ea46001f9cf2ea394cf332980260253.png)

**Suggestions:** Errors seem to point towards some kind of mono incompatibility when it comes to the Windows branch of FiveM. This might be me doing something incorrectly, or maybe not. Let me know if you need anything else to help.

**Comment by GHMatti** [comment]
I think the way you call it from C# is the issue. You extend with BaseScript and it provides Exports automatically, afaik.
