### ISSUE TITLE
need update

### ISSUE THREAD

**Issue by ddevil345** [GHMatti/ghmattimysql#23]
node:4838) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:4838) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:4838) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
(node:4838) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
(node:4838) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
(node:4838) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

**Comment by Th3FearLess1** [comment]
i have this too

**Comment by GHMatti** [comment]
Updated and closed
