### ISSUE TITLE
A DB Ready hook

### ISSUE THREAD

**Issue by sangyoo91** [GHMatti/ghmattimysql#27]
Is there a onDatabaseReady hook?

**Comment by rivor** [comment]
Doesn't seem like it does but you can do something like this
`let mysqlready = (callback) => {
	let tick = setTick(() => {
		while (GetResourceState('mysql') != 'started') {
			Wait(0)
		}
		callback();
		clearTick(tick)
	})
}`

**Comment by sangyoo91** [comment]
thank you ! I hope it gets updated
