### ISSUE TITLE
High Tick

### ISSUE THREAD

**Issue by Nukkle134** [GHMatti/ghmattimysql#30]
Good,
I deduced on Tuesday night a possible problem in GHmattySQL.

This is a high tick expense on the WPA, as shown below.

And causes server thread hitch warning on my server
Hosted in a Dedicated located in Canada. 250up/1gDownload
Thank you
![Capturar](https://user-images.githubusercontent.com/55332994/84209879-a09d5e80-aa8d-11ea-8eba-f51b85ea52e9.PNG)

**Comment by GHMatti** [comment]
That is the wrong resource, the old one is not maintained anymore.

https://github.com/GHMatti/FiveM-MySQL

**Comment by Nukkle134** [comment]
thank you!
