### ISSUE TITLE
Cant get it to load?

### ISSUE THREAD

**Issue by leepafc2** [GHMatti/ghmattimysql#4]
Hello I have done everything that is written and still it wont let me load it? It says cant start resource? 

What am I doing wrong?

Please add me on discord if u have it. 👽leepafc2👽#3411 thank you.

**Comment by leepafc2** [comment]
![this correct](https://user-images.githubusercontent.com/38616900/47874922-01be7400-de0d-11e8-91b2-7e7215e5841c.PNG)


Sorry I forgot to upload the picture, lol. Here can you tell me if im doing this right please? Im trying to get cops_fivem working. This is required for it to work. 

Many thanks. (PS: If your on discord you can add me if you like....👽leepafc2👽#3411

Thank you for replying.

**Comment by GHMatti** [comment]
```
set mysql_connection_string "mysql://mysqluser:password@localhost/database"
```
should be enough

**Comment by leepafc2** [comment]
ok let me try that, also in my current cmd its showing me this....

![screenshot 2](https://user-images.githubusercontent.com/38616900/47875151-b5276880-de0d-11e8-8bdf-6178966c8320.PNG)

**Comment by GHMatti** [comment]
How about you download a release instead?

https://github.com/GHMatti/ghmattimysql/releases

**Comment by leepafc2** [comment]
Thank you dude sorry to be a pain just annoying. Thanks for the help. :)
