### ISSUE TITLE
Error loading script ghmattimysql.lua in resource ghmattimysql

### ISSUE THREAD

**Issue by itsDaveLadd** [GHMatti/ghmattimysql#9]
While installing your script i have ran into this error.

i am using v1.1.0, tried reinstalling it a couple of times.
Thank you in advanced

![image](https://user-images.githubusercontent.com/17910447/49961529-c71b2180-ff0a-11e8-9b55-4b0ab3639e7b.png)

**Comment by iZerkahh** [comment]
i also have this same problem

**Comment by GHMatti** [comment]
Any more information? Did you try deleting the cache folder?
